### ISSUE TITLE
RNN module weights are not part of single contiguous chunk of memory(GPU)

### ISSUE THREAD

**Issue by realiti4** [keitakurita/Better_LSTM_PyTorch#4]
Hi, first of all thanks this is very useful, I was able to tested it on cpu and it stablized the network a lot. My problem is I get the following error when I try to run it on gpu. It continues to run but gives this error many times. I've tried to add 'self.lstm.flatten_parameters()' just before it, it didn't help. I'm testing this on a really simple example with 1 lstm and 1 linear.

    UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().

**Comment by davda54** [comment]
Hey, I've made a pull request #5 that also addresses your issue. You just have to flatten the parameters AFTER dropping the weights :)

**Comment by realiti4** [comment]
> Hey, I've made a pull request #5 that also addresses your issue. You just have to flatten the parameters AFTER dropping the weights :)

Hi, thanks this fixes the issue.
